<a href="https://colab.research.google.com/github/affreen/affreen_ai_ml/blob/create_model/02_practice_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np

my_list = [1,2,2,6] # one dimension

my_list = [[1,2,2,6],[5,6,7]]  # multi dimensional array

In [10]:
# create numpy array
np1 = np.random.rand(3,4)
np1


array([[0.78047878, 0.37418849, 0.10187705, 0.5611798 ],
       [0.04917409, 0.88588815, 0.12616082, 0.56939732],
       [0.12239563, 0.77336119, 0.08909095, 0.27145428]])

In [9]:
# create 2 dimenional tensor

tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.1675,  0.8655,  0.1463, -0.3415],
        [-1.3883, -0.2603, -0.6659, -1.2599],
        [-0.8816, -0.0290,  0.9910,  0.2480]])

In [12]:
# create 3 dimensional tensor
tensor_3d = torch.randn(4,6,7)
tensor_3d

tensor([[[-1.1157, -0.4075,  2.2559,  0.7476, -0.6264,  0.5478, -1.1561],
         [-0.2634, -0.6361,  2.7698,  0.0239,  0.1722, -0.5498, -0.8317],
         [-0.7306, -0.1519, -1.4866, -1.3875,  0.6755,  0.5624,  1.3555],
         [ 1.5451, -0.3617,  1.8473, -1.3811,  0.0763, -0.2164, -0.2036],
         [ 2.1629,  1.0689,  1.2243, -0.4062, -1.0415,  1.3521,  0.8575],
         [ 1.5268,  2.3807,  2.1389,  0.5925,  1.2615, -1.7253, -0.8069]],

        [[ 0.8950,  0.2934,  0.2481,  0.6399,  0.9261,  0.2087,  0.2419],
         [-0.2634,  0.5438,  0.1006, -0.2901,  0.2247, -0.7087,  0.1440],
         [ 1.6677,  1.0447, -0.0510,  1.7171,  1.4878,  0.5670, -1.0723],
         [-0.0151,  0.5936,  1.3826,  0.4045,  1.1759,  0.7421,  0.0848],
         [ 1.1036, -1.9554, -1.6444, -0.1680, -0.9346, -0.4867, -1.0993],
         [ 2.0751, -1.1089,  1.5528,  0.0043,  1.8143, -0.4487,  0.3576]],

        [[-0.4327,  0.5528, -0.7606, -1.3421, -0.7311,  0.2171, -0.6077],
         [-0.8578, -1.1812,  1.166

In [13]:
# create 4 dimensional array
tensor_4d = torch.randn(5,6,2,3)
tensor_4d

tensor([[[[ 2.1215, -0.5169,  0.9515],
          [ 0.6826,  1.0508, -0.6336]],

         [[-0.4009,  2.4237,  1.4231],
          [ 0.2280, -2.0883,  1.4225]],

         [[-0.2182, -0.0939, -1.2765],
          [ 0.2667,  0.2901, -0.6825]],

         [[-0.1708,  0.2863,  0.3694],
          [ 0.1327,  1.4432,  0.7839]],

         [[ 0.7872, -0.9091,  0.1465],
          [-0.7215,  0.0675,  0.6829]],

         [[-0.3763, -0.0407,  1.0968],
          [ 0.6498, -0.3863,  0.2570]]],


        [[[ 0.1102,  0.0093, -0.7856],
          [ 1.1674,  0.7554,  0.1587]],

         [[ 1.4657, -0.2689, -2.0246],
          [-0.0785,  0.6860,  0.8134]],

         [[ 0.2255, -0.9625,  0.0665],
          [ 1.0583,  0.3324,  1.3873]],

         [[ 1.0476, -0.1010,  0.7465],
          [ 1.0955,  0.6234,  1.0260]],

         [[ 0.2634,  0.3294,  0.9216],
          [ 1.8643,  1.0743, -1.3170]],

         [[-0.4883,  0.9438, -0.2758],
          [ 0.7376, -0.0535, -0.3604]]],


        [[[ 0.0444, -1.7385, -2.2886

In [15]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7805, 0.3742, 0.1019, 0.5612],
        [0.0492, 0.8859, 0.1262, 0.5694],
        [0.1224, 0.7734, 0.0891, 0.2715]], dtype=torch.float64)