<a href="https://colab.research.google.com/github/affreen/affreen_ai_ml/blob/create_model/04_practice_tensor_dimensions_elements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch

tensor_A = torch.tensor(8)
print(tensor_A)
print(tensor_A.ndim) # calculate the dimenison of this tensor , returns 0
print(tensor_A.shape)


tensor(8)
0
torch.Size([])


In [11]:
tensor_B = torch.tensor([[[1,2,3],
                          [4,5,6],
                          [7,8,9]]])
print(tensor_B)
print(tensor_B.ndim) # calculate the dimenison of this tensor , returns 3
print(tensor_B.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [20]:
tensor_C = torch.tensor([[[[1,2,3,4],
                           [4,5,6,7],
                           [8,9,1,9],
                           ],
                          [[11,12,13,14],
                           [41,51,61,71],
                           [81,91,10,19],
                           ]]])
print(tensor_C)
print(tensor_C.ndim)
print(tensor_C.shape)
print(tensor_C[0])
print(tensor_C[0][0])
print(tensor_C[0][0][0])
print(tensor_C[0][0][0][0])

tensor([[[[ 1,  2,  3,  4],
          [ 4,  5,  6,  7],
          [ 8,  9,  1,  9]],

         [[11, 12, 13, 14],
          [41, 51, 61, 71],
          [81, 91, 10, 19]]]])
4
torch.Size([1, 2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 8,  9,  1,  9]],

        [[11, 12, 13, 14],
         [41, 51, 61, 71],
         [81, 91, 10, 19]]])
tensor([[1, 2, 3, 4],
        [4, 5, 6, 7],
        [8, 9, 1, 9]])
tensor([1, 2, 3, 4])
tensor(1)
