<a href="https://colab.research.google.com/github/affreen/affreen_ai_ml/blob/create_model/04_practice_tensor_dimensions_elements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

tensor_A = torch.tensor(8)
print(tensor_A)
print(tensor_A.ndim) # calculate the dimenison of this tensor , returns 0
print(tensor_A.shape)


tensor(8)
0
torch.Size([])


In [3]:
tensor_B = torch.tensor([[[1,2,3],
                          [4,5,6],
                          [7,8,9]]])
print(tensor_B)
print(tensor_B.ndim) # calculate the dimenison of this tensor , returns 3
print(tensor_B.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [4]:
tensor_C = torch.tensor([[[[1,2,3,4],
                           [4,5,6,7],
                           [8,9,1,9],
                           ],
                          [[11,12,13,14],
                           [41,51,61,71],
                           [81,91,10,19],
                           ]]])
print(tensor_C)
print(tensor_C.ndim)
print(tensor_C.shape)
print(tensor_C[0])
print(tensor_C[0][0])
print(tensor_C[0][0][0])
print(tensor_C[0][0][0][0])

tensor([[[[ 1,  2,  3,  4],
          [ 4,  5,  6,  7],
          [ 8,  9,  1,  9]],

         [[11, 12, 13, 14],
          [41, 51, 61, 71],
          [81, 91, 10, 19]]]])
4
torch.Size([1, 2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 8,  9,  1,  9]],

        [[11, 12, 13, 14],
         [41, 51, 61, 71],
         [81, 91, 10, 19]]])
tensor([[1, 2, 3, 4],
        [4, 5, 6, 7],
        [8, 9, 1, 9]])
tensor([1, 2, 3, 4])
tensor(1)


In [63]:
tensor_D = torch.tensor([
                           [[
                            [[1,2,3],
                            [4,5,6],
                            [7,8,9]],

                            [[11,12,13],
                            [41,51,61],
                            [81,91,21]],

                            [[62,54,89],
                             [76,65,56],
                             [67,78,89]]
                           ]],
                           [[
                            [[101,201,301],
                            [401,501,601],
                            [701,801,901]],

                           [[110,120,130],
                            [410,510,610],
                            [810,910,210]],

                            [[629,549,899],
                             [769,659,569],
                             [679,789,899]]
                           ]]

                         ])
#print(tensor_D)
print(tensor_D.ndim)
print(tensor_D.shape)
# print(tensor_D[0][0][0][0][0])
print(tensor_D[:, :, :, :, :])

5
torch.Size([2, 1, 3, 3, 3])
tensor([[[[[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9]],

          [[ 11,  12,  13],
           [ 41,  51,  61],
           [ 81,  91,  21]],

          [[ 62,  54,  89],
           [ 76,  65,  56],
           [ 67,  78,  89]]]],



        [[[[101, 201, 301],
           [401, 501, 601],
           [701, 801, 901]],

          [[110, 120, 130],
           [410, 510, 610],
           [810, 910, 210]],

          [[629, 549, 899],
           [769, 659, 569],
           [679, 789, 899]]]]])


In [74]:
tensor_E = torch.tensor([[
                        [1,2,3,4,5],
                         [11,12,13,14,15],
                         [21,22,23,24,25],
                         [31,32,33,34,35],
                         [41,42,43,44,45]
                        ],
                        [
                         [51,52,53,54,55],
                         [61,62,63,64,65],
                         [71,72,73,74,75],
                         [81,82,83,84,85],
                         [91,92,93,94,95]
                         ],
                        [
                         [101,102,103,104,105],
                         [17,21,31,46,58],
                         [18,288,3,41,567],
                         [10,2,38,40,4445],
                         [1,2222,30,41,599]
                         ]])

print(tensor_E.ndim)
print(tensor_E.shape)
print(tensor_E[:, :, :])

3
torch.Size([3, 5, 5])
tensor([[[   1,    2,    3,    4,    5],
         [  11,   12,   13,   14,   15],
         [  21,   22,   23,   24,   25],
         [  31,   32,   33,   34,   35],
         [  41,   42,   43,   44,   45]],

        [[  51,   52,   53,   54,   55],
         [  61,   62,   63,   64,   65],
         [  71,   72,   73,   74,   75],
         [  81,   82,   83,   84,   85],
         [  91,   92,   93,   94,   95]],

        [[ 101,  102,  103,  104,  105],
         [  17,   21,   31,   46,   58],
         [  18,  288,    3,   41,  567],
         [  10,    2,   38,   40, 4445],
         [   1, 2222,   30,   41,  599]]])
