In [24]:
import torch

In [25]:
scaler = torch.tensor(7)
scaler

# get dimension
print(f"Dimension of scaler is {scaler.ndim}")

# get element from tensor
print(f"Element from scalaer is {scaler.item()}")

Dimension of scaler is 0
Element from scalaer is 7


In [26]:
vector = torch.tensor([7,7])
# get dimension
print(f"Dimension of vector is {vector.ndim} and shape is {vector.shape}")

Dimension of vector is 1 and shape is torch.Size([2])


In [27]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(f"Dimension of MATRIX is {MATRIX.ndim} and shape is {MATRIX.shape}")

MATRIX_1 = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
print(f"Dimension of MATRIX_1 is {MATRIX_1.ndim} and shape is {MATRIX_1.shape}")

MATRIX_2 = torch.tensor([[[5,6],
                          [7,8],
                          [0,8]]])

Dimension of MATRIX is 2 and shape is torch.Size([2, 2])
Dimension of MATRIX_1 is 2 and shape is torch.Size([3, 2])


In [28]:
TENSOR = torch.tensor([[[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       [[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       ]])

print(f"Dimension of TENSOR is {TENSOR.ndim} and shape is {TENSOR.shape}")
print(TENSOR[0])

Dimension of TENSOR is 4 and shape is torch.Size([1, 2, 3, 3])
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [51]:
# Generate random tensor

RANDOM_TENSOR = torch.rand(3,4,7)
print(RANDOM_TENSOR)
print(f"Dimension of RANDOM_TENSOR is {RANDOM_TENSOR.ndim} and shape is {RANDOM_TENSOR.shape}")

tensor([[[0.3766, 0.1647, 0.7212, 0.7245, 0.7334, 0.5747, 0.6183],
         [0.5205, 0.9055, 0.4589, 0.4391, 0.6218, 0.5201, 0.3854],
         [0.7485, 0.3918, 0.1234, 0.5938, 0.7007, 0.1952, 0.2533],
         [0.3273, 0.8376, 0.7682, 0.8928, 0.3946, 0.9746, 0.8135]],

        [[0.0848, 0.5569, 0.2542, 0.2688, 0.0641, 0.6807, 0.4747],
         [0.2552, 0.9355, 0.1767, 0.4303, 0.1905, 0.1854, 0.0928],
         [0.4754, 0.0425, 0.1835, 0.6035, 0.9121, 0.0119, 0.1205],
         [0.1800, 0.3501, 0.5298, 0.5724, 0.1229, 0.2419, 0.1716]],

        [[0.9044, 0.7542, 0.4492, 0.2695, 0.9660, 0.8752, 0.3170],
         [0.6469, 0.4412, 0.2871, 0.4296, 0.7213, 0.1894, 0.3319],
         [0.1694, 0.2900, 0.5135, 0.9794, 0.0952, 0.2466, 0.8996],
         [0.8370, 0.0241, 0.8073, 0.9460, 0.8998, 0.4899, 0.5579]]])
Dimension of RANDOM_TENSOR is 3 and shape is torch.Size([3, 4, 7])


In [56]:
# create random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
print(random_image_tensor)
print(f"Dimension of random_image_tensor is {random_image_tensor.ndim} and shape is {random_image_tensor.shape}")

tensor([[[0.2758, 0.3919, 0.1811],
         [0.8844, 0.6234, 0.8750],
         [0.8099, 0.9268, 0.7739],
         ...,
         [0.4116, 0.2428, 0.8218],
         [0.2576, 0.4289, 0.8430],
         [0.1891, 0.2961, 0.3595]],

        [[0.7186, 0.5980, 0.5718],
         [0.8638, 0.4879, 0.3190],
         [0.6076, 0.9023, 0.6077],
         ...,
         [0.0632, 0.3627, 0.1348],
         [0.7675, 0.4531, 0.1075],
         [0.4180, 0.9396, 0.5681]],

        [[0.6666, 0.5861, 0.0085],
         [0.7700, 0.5289, 0.3099],
         [0.8906, 0.8775, 0.4233],
         ...,
         [0.8437, 0.6948, 0.4379],
         [0.7239, 0.7439, 0.8823],
         [0.8263, 0.6156, 0.9249]],

        ...,

        [[0.8449, 0.4685, 0.0537],
         [0.8727, 0.2913, 0.5150],
         [0.6160, 0.7530, 0.4178],
         ...,
         [0.8741, 0.8395, 0.2314],
         [0.2897, 0.3594, 0.1265],
         [0.5087, 0.2679, 0.7662]],

        [[0.5368, 0.0828, 0.3535],
         [0.5479, 0.4614, 0.1610],
         [0.

In [58]:
# create tensor with zeroes and ones

zero = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
print(zero)
print(ones)
print(zero.dtype)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.float32


In [65]:
# create range of tensors
tensor_range = torch.arange(start=0,end=10,step=1)
print(tensor_range)

tensor_range_1 = torch.arange(start=20,end=40,step=5)
print(tensor_range_1)
print(f"Data type: {tensor_range_1.dtype}")
print(f"Dimension: {tensor_range_1.ndim}")




tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([20, 25, 30, 35])
Data type: torch.int64
Dimension: 1
tensor([0, 0, 0, 0])


In [66]:
# create tensor like

ten_zeroes = torch.zeros_like(input=tensor_range)
print(ten_zeroes)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
