<a href="https://colab.research.google.com/github/affreen/affreen_ai_ml/blob/create_model/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


In [118]:
scaler = torch.tensor(7)
scaler

# get dimension
print(f"Dimension of scaler is {scaler.ndim}")

# get element from tensor
print(f"Element from scalaer is {scaler.item()}")

Dimension of scaler is 0
Element from scalaer is 7


In [119]:
vector = torch.tensor([7,7])
# get dimension
print(f"Dimension of vector is {vector.ndim} and shape is {vector.shape}")

Dimension of vector is 1 and shape is torch.Size([2])


In [120]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(f"Dimension of MATRIX is {MATRIX.ndim} and shape is {MATRIX.shape}")

MATRIX_1 = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
print(f"Dimension of MATRIX_1 is {MATRIX_1.ndim} and shape is {MATRIX_1.shape}")

MATRIX_2 = torch.tensor([[[5,6],
                          [7,8],
                          [0,8]]])

Dimension of MATRIX is 2 and shape is torch.Size([2, 2])
Dimension of MATRIX_1 is 2 and shape is torch.Size([3, 2])


In [121]:
TENSOR = torch.tensor([[[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       [[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       ]])

print(f"Dimension of TENSOR is {TENSOR.ndim} and shape is {TENSOR.shape}")
print(TENSOR[0])

Dimension of TENSOR is 4 and shape is torch.Size([1, 2, 3, 3])
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [122]:
# Generate random tensor

RANDOM_TENSOR = torch.rand(3,4,7)
print(RANDOM_TENSOR)
print(f"Dimension of RANDOM_TENSOR is {RANDOM_TENSOR.ndim} and shape is {RANDOM_TENSOR.shape}")

tensor([[[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423]],

        [[0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315],
         [0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036]],

        [[0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
         [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
         [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
         [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331]]])
Dimension of RANDOM_TENSOR is 3 and shape is torch.Size([3, 4, 7])


In [123]:
# create random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
print(random_image_tensor)
print(f"Dimension of random_image_tensor is {random_image_tensor.ndim} and shape is {random_image_tensor.shape}")

tensor([[[0.9578, 0.3313, 0.3227],
         [0.0162, 0.2137, 0.6249],
         [0.4340, 0.1371, 0.5117],
         ...,
         [0.9856, 0.2502, 0.3799],
         [0.3647, 0.1742, 0.0094],
         [0.7819, 0.6328, 0.0317]],

        [[0.1782, 0.9942, 0.6911],
         [0.7006, 0.2009, 0.2808],
         [0.4245, 0.4086, 0.1574],
         ...,
         [0.7862, 0.6386, 0.9695],
         [0.0469, 0.5807, 0.8201],
         [0.8321, 0.1021, 0.6779]],

        [[0.2152, 0.4805, 0.3957],
         [0.0825, 0.0230, 0.1711],
         [0.7269, 0.7287, 0.0651],
         ...,
         [0.2948, 0.4013, 0.7430],
         [0.4885, 0.9276, 0.4711],
         [0.4283, 0.7822, 0.4871]],

        ...,

        [[0.5978, 0.2830, 0.0132],
         [0.4554, 0.8851, 0.7749],
         [0.7240, 0.6918, 0.4109],
         ...,
         [0.6640, 0.6155, 0.6034],
         [0.7384, 0.0507, 0.1781],
         [0.1079, 0.1586, 0.9476]],

        [[0.9360, 0.3383, 0.1574],
         [0.0051, 0.3240, 0.3198],
         [0.

In [124]:
# create tensor with zeroes and ones

zero = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
print(zero)
print(ones)
print(zero.dtype)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.float32


In [125]:
# create range of tensors
tensor_range = torch.arange(start=0,end=10,step=1)
print(tensor_range)

tensor_range_1 = torch.arange(start=20,end=40,step=5)
print(tensor_range_1)
print(f"Data type: {tensor_range_1.dtype}")
print(f"Dimension: {tensor_range_1.ndim}")




tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([20, 25, 30, 35])
Data type: torch.int64
Dimension: 1


In [126]:
# create tensor like

ten_zeroes = torch.zeros_like(input=tensor_range)
print(ten_zeroes)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [127]:
# convert numpy into tensors and vice versa

# Numpy is a popular scitentifc Python numerical computing library. And due to this PyTorch needs intercation with numpy array.

array = np.arange(1.0, 8.0)
array

tensor = torch.from_numpy(array) # convert numpy array into tensor
print(f" tensor: {tensor} array: {array}") # pytorch is going to retain the default data type defined from numpy array which float64 unless specified otherwise


# default data type in numpy array is 'float64'
print(f"default data type of numpy array is: {array.dtype}")

# default data type in pytorch is 'float32'
my_torch = torch.ones(7)
print(f"default data type of pytorch is: {my_torch.dtype}")


# change the data type while converting numpy array into tensor
array_1  = np.arange(11.0, 20.0)
tensor_1 = torch.from_numpy(array_1).type(torch.float32)
print(f" tensor: {tensor_1}; tensor data type: {tensor_1.dtype} array: {array_1}; array data type: {array_1.dtype}")


# changing  the value of array doesn't change the value of the tensor
array_1 = array_1 + 1
print(f"array_1 : {array_1}")
print(f" tensor: {tensor_1}")

# convert tensor into numpy array - and
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(f"Numpy array: {numpy_tensor}; data type: {numpy_tensor.dtype}") # data type in converted array would be set to the original data type set for tensor which is float32 in this case

# change the value of tensor
tensor = tensor + 1

print(f"numpy array: {numpy_tensor}")

 tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) array: [1. 2. 3. 4. 5. 6. 7.]
default data type of numpy array is: float64
default data type of pytorch is: torch.float32
 tensor: tensor([11., 12., 13., 14., 15., 16., 17., 18., 19.]); tensor data type: torch.float32 array: [11. 12. 13. 14. 15. 16. 17. 18. 19.]; array data type: float64
array_1 : [12. 13. 14. 15. 16. 17. 18. 19. 20.]
 tensor: tensor([11., 12., 13., 14., 15., 16., 17., 18., 19.])
Numpy array: [1. 1. 1. 1. 1. 1. 1.]; data type: float32
numpy array: [1. 1. 1. 1. 1. 1. 1.]


In [128]:
## Reproducibility (trying to take random out of random) - leverage random seed

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A: {random_tensor_A}")
print(f"Tensor B: {random_tensor_B}")
print(f"Does Tensor A equal Tensor B? (anywhere)")
print(random_tensor_A == random_tensor_B)

# lets make reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor C: {random_tensor_C}")
print(f"Tensor D: {random_tensor_D}")
print(f"Does Tensor C equal Tensor D? (anywhere)")
print(random_tensor_C == random_tensor_D)


Tensor A: tensor([[0.5912, 0.8892, 0.4251, 0.8701],
        [0.1472, 0.6981, 0.4965, 0.0381],
        [0.8473, 0.4449, 0.0770, 0.4626]])
Tensor B: tensor([[0.7900, 0.2483, 0.8160, 0.1168],
        [0.9158, 0.9107, 0.8897, 0.5155],
        [0.5067, 0.7787, 0.9570, 0.2658]])
Does Tensor A equal Tensor B? (anywhere)
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
Tensor C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Does Tensor C equal Tensor D? (anywhere)
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [129]:
# Selecting data from tensors (indexing)

x = torch.arange(1, 10).reshape(1, 3, 3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [130]:
# Retrieve elements from index 0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [131]:
# retrieve elements from middle bracket (dim=1)
x[0][0]

# also written as
x[0, 0]

tensor([1, 2, 3])

In [132]:
# retrieve elements from the inner bracket (dim=2)
x[0][0][0]
x[0][0][1]
x[0][0][2]
x[0][2][2] # --> gives number

tensor(9)

In [133]:
# use ':' to select all elements from a given dimension
x[:, 0] # select all elements from dim=0

tensor([[1, 2, 3]])

In [134]:
# get all elements of 0th and 1st dimensions and print only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [135]:
# get all elements of 0th dim and print only index values of 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [136]:
# get index 0 of 0th and 1st dim amd all value of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [137]:
# Index on torch x to return the value 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of input tensor of certain shpae but retain the memory of the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of input tensor with dimensions permuted (swapped) in a specified way



In [138]:
# Lets create a tensor
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [145]:
# add an extra dimension, reshape has to be compatible with the original size
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(9, 1)
print(x_reshaped, x_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])


In [147]:
# change the view, (changing z changes x because a view of the tensor shares the same original memory)
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))