<a href="https://colab.research.google.com/github/affreen/affreen_ai_ml/blob/create_model/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


In [2]:
scaler = torch.tensor(7)
scaler

# get dimension
print(f"Dimension of scaler is {scaler.ndim}")

# get element from tensor
print(f"Element from scalaer is {scaler.item()}")

Dimension of scaler is 0
Element from scalaer is 7


In [3]:
vector = torch.tensor([7,7])
# get dimension
print(f"Dimension of vector is {vector.ndim} and shape is {vector.shape}")

Dimension of vector is 1 and shape is torch.Size([2])


In [4]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(f"Dimension of MATRIX is {MATRIX.ndim} and shape is {MATRIX.shape}")

MATRIX_1 = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
print(f"Dimension of MATRIX_1 is {MATRIX_1.ndim} and shape is {MATRIX_1.shape}")

MATRIX_2 = torch.tensor([[[5,6],
                          [7,8],
                          [0,8]]])

Dimension of MATRIX is 2 and shape is torch.Size([2, 2])
Dimension of MATRIX_1 is 2 and shape is torch.Size([3, 2])


In [5]:
TENSOR = torch.tensor([[[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       [[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       ]])

print(f"Dimension of TENSOR is {TENSOR.ndim} and shape is {TENSOR.shape}")
print(TENSOR[0])

Dimension of TENSOR is 4 and shape is torch.Size([1, 2, 3, 3])
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [6]:
# Generate random tensor

RANDOM_TENSOR = torch.rand(3,4,7)
print(RANDOM_TENSOR)
print(f"Dimension of RANDOM_TENSOR is {RANDOM_TENSOR.ndim} and shape is {RANDOM_TENSOR.shape}")

tensor([[[0.3834, 0.3457, 0.3569, 0.0275, 0.0018, 0.9622, 0.0898],
         [0.0571, 0.1398, 0.4428, 0.4324, 0.2159, 0.9486, 0.9300],
         [0.2379, 0.9971, 0.3959, 0.1561, 0.2275, 0.6227, 0.7107],
         [0.5544, 0.2186, 0.5888, 0.9883, 0.6062, 0.6915, 0.3481]],

        [[0.2696, 0.4777, 0.2391, 0.4855, 0.9894, 0.0592, 0.2294],
         [0.0592, 0.0993, 0.4489, 0.0837, 0.8715, 0.6290, 0.3582],
         [0.6734, 0.6281, 0.9566, 0.4440, 0.7496, 0.4805, 0.6190],
         [0.4834, 0.2708, 0.3350, 0.1783, 0.5871, 0.8879, 0.7093]],

        [[0.7345, 0.2189, 0.2965, 0.1109, 0.3775, 0.4816, 0.0899],
         [0.3797, 0.8301, 0.2468, 0.1595, 0.0363, 0.5425, 0.6489],
         [0.1809, 0.5656, 0.0634, 0.7959, 0.9711, 0.2775, 0.7140],
         [0.6131, 0.2264, 0.6771, 0.5870, 0.1374, 0.6306, 0.6368]]])
Dimension of RANDOM_TENSOR is 3 and shape is torch.Size([3, 4, 7])


In [7]:
# create random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
print(random_image_tensor)
print(f"Dimension of random_image_tensor is {random_image_tensor.ndim} and shape is {random_image_tensor.shape}")

tensor([[[0.2093, 0.7799, 0.9946],
         [0.6100, 0.0059, 0.4577],
         [0.1088, 0.3850, 0.2541],
         ...,
         [0.6785, 0.6926, 0.0217],
         [0.0034, 0.1648, 0.5679],
         [0.2853, 0.4835, 0.9985]],

        [[0.8805, 0.2338, 0.4434],
         [0.9001, 0.2275, 0.7522],
         [0.8623, 0.9303, 0.8265],
         ...,
         [0.8484, 0.9888, 0.4824],
         [0.8869, 0.1187, 0.1230],
         [0.9400, 0.2351, 0.5372]],

        [[0.5826, 0.5716, 0.2726],
         [0.1826, 0.8256, 0.6412],
         [0.2797, 0.5113, 0.6128],
         ...,
         [0.4247, 0.5461, 0.6567],
         [0.5579, 0.0132, 0.3676],
         [0.3089, 0.8257, 0.2474]],

        ...,

        [[0.4768, 0.8642, 0.9665],
         [0.2892, 0.6413, 0.0207],
         [0.4847, 0.2125, 0.2579],
         ...,
         [0.5665, 0.4623, 0.5224],
         [0.3361, 0.0403, 0.7819],
         [0.7478, 0.7288, 0.3518]],

        [[0.9519, 0.3479, 0.1577],
         [0.8449, 0.3290, 0.7393],
         [0.

In [8]:
# create tensor with zeroes and ones

zero = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
print(zero)
print(ones)
print(zero.dtype)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.float32


In [9]:
# create range of tensors
tensor_range = torch.arange(start=0,end=10,step=1)
print(tensor_range)

tensor_range_1 = torch.arange(start=20,end=40,step=5)
print(tensor_range_1)
print(f"Data type: {tensor_range_1.dtype}")
print(f"Dimension: {tensor_range_1.ndim}")




tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([20, 25, 30, 35])
Data type: torch.int64
Dimension: 1


In [10]:
# create tensor like

ten_zeroes = torch.zeros_like(input=tensor_range)
print(ten_zeroes)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [37]:
# convert numpy into tensors and vice versa

# Numpy is a popular scitentifc Python numerical computing library. And due to this PyTorch needs intercation with numpy array.

array = np.arange(1.0, 8.0)
array

tensor = torch.from_numpy(array) # convert numpy array into tensor
print(f" tensor: {tensor} array: {array}") # pytorch is going to retain the default data type defined from numpy array which float64 unless specified otherwise


# default data type in numpy array is 'float64'
print(f"default data type of numpy array is: {array.dtype}")

# default data type in pytorch is 'float32'
my_torch = torch.ones(7)
print(f"default data type of pytorch is: {my_torch.dtype}")


# change the data type while converting numpy array into tensor
array_1  = np.arange(11.0, 20.0)
tensor_1 = torch.from_numpy(array_1).type(torch.float32)
print(f" tensor: {tensor_1}; tensor data type: {tensor_1.dtype} array: {array_1}; array data type: {array_1.dtype}")


# changing  the value of array doesn't change the value of the tensor
array_1 = array_1 + 1
print(f"array_1 : {array_1}")
print(f" tensor: {tensor_1}")

# convert tensor into numpy array - and
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(f"Numpy array: {numpy_tensor}; data type: {numpy_tensor.dtype}") # data type in converted array would be set to the original data type set for tensor which is float32 in this case

# change the value of tensor
tensor = tensor + 1

print(f"numpy array: {numpy_tensor}")

 tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) array: [1. 2. 3. 4. 5. 6. 7.]
default data type of numpy array is: float64
default data type of pytorch is: torch.float32
 tensor: tensor([11., 12., 13., 14., 15., 16., 17., 18., 19.]); tensor data type: torch.float32 array: [11. 12. 13. 14. 15. 16. 17. 18. 19.]; array data type: float64
array_1 : [12. 13. 14. 15. 16. 17. 18. 19. 20.]
 tensor: tensor([11., 12., 13., 14., 15., 16., 17., 18., 19.])
Numpy array: [1. 1. 1. 1. 1. 1. 1.]; data type: float32
numpy array: [1. 1. 1. 1. 1. 1. 1.]
